using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BepInEx;
using StationeersUIMod.Core;

namespace StationeersUIMod.UI.Menu.Tutorial
{
    /// <summary>
    /// Writes the live lesson copy (shipped text + FlorpyDorp's in-game overrides) back out as C#
    /// source in EXACTLY the shape of the shipped <c>UI/Menu/Tutorial/TutorialCopy.g.cs</c>, so
    /// <c>tools/bake-tutorial.ps1</c> can fold an editing session into the repo with no hand
    /// merging. The shape is pinned by <c>Documentation/0.9.8.0/Tutorial-Build-Contract.md</c> s7:
    ///
    /// <para><b>Order.</b> Lessons in <see cref="TutorialChapters.Lessons"/> order - a
    /// <c>// &lt;lessonId&gt; - &lt;title&gt;</c> comment, the lesson title key, then every step's
    /// <see cref="TStep.Fields"/> in array order - then <see cref="TutorialChapters.TipKeys"/>, then
    /// <see cref="TutorialChapters.ChromeKeys"/>. Each pair is the key and
    /// <see cref="TutorialTextStore.Get"/> for it (override, else shipped default).</para>
    ///
    /// <para><b>Bytes.</b> ASCII only, CRLF line endings, no BOM, a final CRLF. Inside a string
    /// literal the ONLY escapes are <c>\\</c>, <c>\"</c> and <c>\n</c>. With zero overrides the
    /// output reproduces the repo file byte for byte - that is the round-trip test, and the reason
    /// every literal line below is a constant rather than something "tidied" per export.</para>
    ///
    /// <para><b>Defence in depth.</b> The text store already sanitises (non-ASCII -> '?', CR and
    /// other control chars dropped), but this writer re-applies the same rule so a bad string can
    /// never produce a file that fails to compile: a raw CR or LF inside a C# string literal is a
    /// compile error, and a '"' would end the literal early.</para>
    ///
    /// <para>Pure file output: no game state, no Unity objects, no statics - nothing to reset on a
    /// hot reload. Runs only when the editor's Export button is pressed (never per frame).</para>
    /// </summary>
    internal static class TutorialCopyExport
    {
        internal const string FileName = "TutorialCopy.g.cs";

        private const string NL = "\r\n";
        private const string PairIndent = "            ";   // 12 spaces: inside the Pairs initializer

        // The fixed frame of the file. Keep these byte-identical to the repo's TutorialCopy.g.cs:
        // the zero-override export must reproduce it exactly (contract s7).
        private static readonly string[] Head =
        {
            "// <auto-generated> UIA lesson copy. Edit in game (uiadev, then uiatutorial edit), then run",
            "// tools/bake-tutorial.ps1. Hand edits here are fine but get reformatted by the next export.",
            "// ASCII only. Pairs: key, text. Key grammar: see Documentation/0.9.8.0/Tutorial-Build-Contract.md s6.",
            "namespace StationeersUIMod.UI.Menu.Tutorial",
            "{",
            "    internal static class TutorialCopy",
            "    {",
            "        internal static readonly string[] Pairs =",
            "        {",
        };

        private static readonly string[] Tail =
        {
            "        };",
            "    }",
            "}",
        };

        /// <summary>What one export wrote, for the editor's status line.</summary>
        internal struct Summary
        {
            internal int Pairs;          // key/text pairs written
            internal int Edited;         // of those, how many carry an override
            internal int Orphans;        // overrides whose key is in no lesson/tip/chrome list (not written)
            internal int Duplicates;     // keys written more than once (a data bug - bake refuses the file)
            internal string FirstDuplicate;
            internal int SkippedEmptyKeys;
        }

        /// <summary><c>BepInEx/config/StationeersUIMod/Tutorial/Export</c> - beside the override file,
        /// resolved the same way <see cref="TutorialTextStore"/> resolves its folder.</summary>
        internal static string ExportDir
        {
            get { return Path.Combine(Path.Combine(Path.Combine(Paths.ConfigPath, "StationeersUIMod"), "Tutorial"), "Export"); }
        }

        internal static string ExportPath { get { return Path.Combine(ExportDir, FileName); } }

        /// <summary>Build the whole file in memory. Never throws for bad data (a null lesson, step or
        /// field list is skipped); a missing data class would throw, and <see cref="Export"/> catches.</summary>
        internal static string BuildSource(out Summary summary)
        {
            summary = new Summary();
            var sb = new StringBuilder(96 * 1024);
            var written = new HashSet<string>(StringComparer.Ordinal);

            for (int i = 0; i < Head.Length; i++) Line(sb, Head[i]);

            TLesson[] lessons = TutorialChapters.Lessons;
            if (lessons != null)
            {
                for (int li = 0; li < lessons.Length; li++)
                {
                    TLesson lesson = lessons[li];
                    if (lesson == null) continue;

                    string title = string.IsNullOrEmpty(lesson.TitleKey) ? "" : TutorialTextStore.Get(lesson.TitleKey);
                    sb.Append(PairIndent).Append("// ").Append(CommentSafe(lesson.Id)).Append(" - ")
                      .Append(CommentSafe(title)).Append(NL);

                    if (!string.IsNullOrEmpty(lesson.TitleKey)) Pair(sb, lesson.TitleKey, written, ref summary);

                    TStep[] steps = lesson.Steps;
                    if (steps == null) continue;
                    for (int si = 0; si < steps.Length; si++)
                    {
                        TStep step = steps[si];
                        if (step == null || step.Fields == null) continue;
                        for (int fi = 0; fi < step.Fields.Length; fi++)
                            Pair(sb, step.Fields[fi].Key, written, ref summary);
                    }
                }
            }

            WriteKeyList(sb, TutorialChapters.TipKeys, written, ref summary);
            WriteKeyList(sb, TutorialChapters.ChromeKeys, written, ref summary);

            for (int i = 0; i < Tail.Length; i++) Line(sb, Tail[i]);

            // Overrides the script no longer names (the pre-0.9.8.0 15-step ids, a renamed key) are
            // NOT exported - they would be dead pairs. Counted so the editor can say so out loud.
            try
            {
                foreach (string k in TutorialTextStore.OverriddenKeys)
                    if (!string.IsNullOrEmpty(k) && !written.Contains(k)) summary.Orphans++;
            }
            catch { }

            return sb.ToString();
        }

        /// <summary>Write the export file (via a temp file, so a failed write never leaves a
        /// half-written export for the bake script to pick up). Returns false with a one-line reason
        /// on any failure; logs the full exception.</summary>
        internal static bool Export(out string path, out Summary summary, out string error)
        {
            path = ExportPath;
            summary = new Summary();
            error = null;
            try
            {
                string source = BuildSource(out summary);
                Directory.CreateDirectory(ExportDir);
                string tmp = path + ".tmp";
                // Explicit UTF-8 without a BOM. The content is pure ASCII by construction, so these
                // are also exactly the ASCII bytes.
                File.WriteAllText(tmp, source, new UTF8Encoding(false));
                if (File.Exists(path)) File.Delete(path);
                File.Move(tmp, path);
                UIALog.Info("Tutorial copy exported: " + summary.Pairs + " pair(s), " + summary.Edited
                    + " edited -> " + path);
                return true;
            }
            catch (Exception e)
            {
                error = e.Message;
                UIALog.Error("TutorialCopyExport.Export failed: " + e);
                return false;
            }
        }

        // ------------------------------------------------------------------ helpers

        private static void WriteKeyList(StringBuilder sb, string[] keys, HashSet<string> written, ref Summary summary)
        {
            if (keys == null) return;
            for (int i = 0; i < keys.Length; i++) Pair(sb, keys[i], written, ref summary);
        }

        private static void Pair(StringBuilder sb, string key, HashSet<string> written, ref Summary summary)
        {
            if (string.IsNullOrEmpty(key)) { summary.SkippedEmptyKeys++; return; }

            if (!written.Add(key))
            {
                // Written anyway: the file must mirror the data, and bake-tutorial.ps1 refuses a file
                // with a duplicate key - which is how the data bug gets noticed.
                summary.Duplicates++;
                if (summary.FirstDuplicate == null) summary.FirstDuplicate = key;
            }

            string text = TutorialTextStore.Get(key) ?? "";
            bool edited = false;
            try { edited = TutorialTextStore.IsOverridden(key); } catch { }
            if (edited) summary.Edited++;
            summary.Pairs++;

            sb.Append(PairIndent).Append('"');
            AppendEscaped(sb, key);
            sb.Append("\", \"");
            AppendEscaped(sb, text);
            sb.Append("\",").Append(NL);
        }

        private static void Line(StringBuilder sb, string s)
        {
            sb.Append(s).Append(NL);
        }

        /// <summary>C# string-literal escaping with exactly the three escapes the contract allows.
        /// Anything above 0x7E becomes '?' (the store's rule, so an export can never be less ASCII
        /// than the store); CR and every other control char except TAB are dropped (TAB is legal
        /// inside a regular literal and stays literal).</summary>
        internal static void AppendEscaped(StringBuilder sb, string s)
        {
            if (string.IsNullOrEmpty(s)) return;
            for (int i = 0; i < s.Length; i++)
            {
                char c = s[i];
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    default:
                        if (c > 0x7E) sb.Append('?');
                        else if (c < 0x20 && c != '\t') { /* CR and other control chars: dropped */ }
                        else sb.Append(c);
                        break;
                }
            }
        }

        /// <summary>Text for a <c>//</c> comment line: one line, ASCII. A line break in a title would
        /// otherwise end the comment and turn the rest of the title into code.</summary>
        private static string CommentSafe(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            bool clean = true;
            for (int i = 0; i < s.Length; i++)
            {
                char c = s[i];
                if (c > 0x7E || c < 0x20) { clean = false; break; }
            }
            if (clean) return s;
            var sb = new StringBuilder(s.Length);
            for (int i = 0; i < s.Length; i++)
            {
                char c = s[i];
                if (c == '\n' || c == '\r' || c == '\t') sb.Append(' ');
                else if (c > 0x7E) sb.Append('?');
                else if (c >= 0x20) sb.Append(c);
            }
            return sb.ToString();
        }
    }
}
