// <auto-generated>
// SHIPPED STOW PROFILE PRESETS - the four sets SmartStow B4 seeds onto a player's disk.
//
// AUTHORED FROM (not scraped at runtime):
//   Documentation/SmartStow-Preset-Catalog.md - Part B (the game's 11 SortingClass buckets),
//   Part C (FlorpyDorp's own 9-bag "Ascended" layout - shipped as "Stationpedia Ascended" until
//   2026-09-26, renamed at his request because the long name ellipsized in the F10 layout cards;
//   StowProfileStore.MigrateRenamedShipped carries existing installs over), transcribed rule for rule,
//   Part D (the per-fabricator rosters + its multi-printer PRIMARY resolution table),
//   Part E (the one-bag Starter set). That document is FlorpyDorp-reviewed data.
//   The Part D prefab lists were re-extracted verbatim from the game's own recipe data
//   (<install>/rocketstation_Data/StreamingAssets/Data/*.xml, RecipeData/PrefabName) so every
//   name here is a real prefab, and the catalog's dedupe table was applied on top: every
//   duplicate the extraction found is one the catalog already names (zero unlisted dups).
//
// HAND-SYNC RULE (the UIASortingData.g.cs precedent): there is NO build step behind this file.
// If the catalog document changes, or a game update adds/renames a printed item, this file must
// be REGENERATED/EDITED BY HAND to match - and because Restore shipped Stow Profiles overwrites
// by name, a divergence here silently hands players content the catalog does not describe.
// Bump Revision when the CONTENT changes so the .shipped marker records which vintage a player got.
// A pure RENAME is not a content change and does NOT bump Revision; it needs a one-time on-disk
// migration instead (see StowProfileStore.MigrateRenamedShipped and LegacyAscendedName below),
// because seeding is keyed BY NAME and would otherwise hand an existing player a duplicate.
//
// Deliberately NOT a hash-manifest system (unlike HudProfiles/.shipped-manifest): a Stow Profile
// that is missing or edited degrades gracefully (the router falls through to affinity/defaults),
// so seed-if-absent + an explicit Restore button is the accepted, simpler tradeoff. See the B4
// Changes Report.
// </auto-generated>
using System.Collections.Generic;

namespace StationeersUIMod.Features
{
    /// <summary>The four shipped preset Stow Profiles, built in code. See the header above for
    /// provenance and the hand-sync rule.</summary>
    internal static class ShippedStowProfiles
    {
        /// <summary>Content vintage. Recorded per set in <c>StowProfiles/.shipped</c> so a
        /// player's marker says WHICH version of a set they were given.</summary>
        public const int Revision = 1;

        public const string ByPrinter = "By Printer";
        public const string ByCategory = "By Category";
        /// <summary>FlorpyDorp's own nine-bag layout (catalog Part C).</summary>
        public const string Ascended = "Ascended";
        public const string Starter = "Starter";

        /// <summary>The name <see cref="Ascended"/> SHIPPED UNDER before 2026-09-26. NOT a shipped
        /// name any more (it is deliberately absent from <see cref="Names"/>, so it is never seeded,
        /// restored or labelled as ours) — kept only so
        /// <c>StowProfileStore.MigrateRenamedShipped</c> can recognise and rename an existing
        /// install's copy. A pure NAME change: the content is identical, so
        /// <see cref="Revision"/> did not move.</summary>
        public const string LegacyAscendedName = "Stationpedia Ascended";

        /// <summary>Every shipped set name, in seed/restore order.</summary>
        public static readonly string[] Names = { ByPrinter, ByCategory, Ascended, Starter };

        /// <summary>Build one shipped set by name, or null when the name is not one of ours.</summary>
        public static StowProfileDoc Build(string name)
        {
            if (name == ByPrinter) return BuildByPrinter();
            if (name == ByCategory) return BuildByCategory();
            if (name == Ascended) return BuildAscended();
            if (name == Starter) return BuildStarter();
            return null;
        }

        // ---------- tiny builders (keep the data below readable) ----------

        private static StowProfileDoc Doc(string name, string description)
        {
            return new StowProfileDoc
            {
                Name = name,
                Schema = StowProfileStore.CurrentSchema,
                Description = description,
                Profiles = new List<BagProfile>(),
            };
        }

        private static BagProfile Bag(StowProfileDoc doc, string name, string badge)
        {
            var p = new BagProfile { Name = name, Badge = badge };
            doc.Profiles.Add(p);
            return p;
        }

        private static BagProfile Items(BagProfile p, string[] prefabs, int priority)
        {
            for (int i = 0; i < prefabs.Length; i++)
                p.Items.Add(new ItemRule { Prefab = prefabs[i], Priority = priority });
            return p;
        }

        private static BagProfile Cats(BagProfile p, int priority, params string[] names)
        {
            for (int i = 0; i < names.Length; i++)
                p.Categories.Add(new CategoryRule { Name = names[i], Priority = priority });
            return p;
        }

        private static BagProfile Slots(BagProfile p, int priority, params string[] names)
        {
            for (int i = 0; i < names.Length; i++)
                p.SlotClasses.Add(new SlotClassRule { Name = names[i], Priority = priority });
            return p;
        }

        private static BagProfile Classes(BagProfile p, int priority, params string[] names)
        {
            for (int i = 0; i < names.Length; i++)
                p.UIAClasses.Add(new UIAClassRule { Name = names[i], Priority = priority });
            return p;
        }

        // ================= 1. BY PRINTER (catalog Part D) =================

        /// <summary>One Bag Profile per fabricator, its roster expressed as explicit Item rules
        /// (the only mechanism that can tell a wall kit from a rocket-engine kit - both are
        /// SortingClass=Kits, Slot.Class=None). Catalog Part D's folds are applied: the Automated
        /// Oven (identical 19-item list to the Microwave) and the Arc Furnace (8 items the Furnace
        /// already makes) have ZERO exclusive outputs and get no profile of their own; every
        /// multi-printer item sits in exactly one profile, its catalog-declared PRIMARY. The
        /// Recycler (dynamic, code-driven), the Organics Printer (no recipe data in this build)
        /// and the Paint Mixer (fills an existing can, prints nothing) have no roster to ship.
        /// The Terraforming Manufactory gets no bag either: its only non-duplicate output is
        /// <c>ItemKitDebug</c>, which catalog Part D flags as dev/creative content, and a bag
        /// that can only ever catch one debug kit is noise (it falls to Not Printed).
        /// "Not Printed" is the catch-all home for everything mined/grown/found.</summary>
        private static StowProfileDoc BuildByPrinter()
        {
            var d = Doc(ByPrinter, "One bag per fabricator: every item lands in the bag for the machine that prints it. Anything mined, grown or found goes to Not Printed.");
            Items(Bag(d, "Autolathe", "AUTO"), Autolathe, 100);
            Items(Bag(d, "Tool Manufactory", "TOOL"), ToolManufactory, 100);
            Items(Bag(d, "Security Printer", "SEC"), SecurityPrinter, 100);
            Items(Bag(d, "Electronics Printer", "ELEC"), ElectronicsPrinter, 100);
            Items(Bag(d, "Hydraulic Pipe Bender", "PIPE"), HydraulicPipeBender, 100);
            Items(Bag(d, "Rocket Manufactory", "RKT"), RocketManufactory, 100);
            Items(Bag(d, "Furnace", "FURN"), Furnace, 100);
            Items(Bag(d, "Advanced Furnace", "ADVF"), AdvancedFurnace, 100);
            Items(Bag(d, "Centrifuge", "CENT"), Centrifuge, 100);
            Items(Bag(d, "Chemistry Set", "CHEM"), ChemistrySet, 100);
            Items(Bag(d, "Reagent Grinder", "GRND"), ReagentGrinder, 100);
            Items(Bag(d, "Microwave", "MICR"), Microwave, 100);
            Items(Bag(d, "Packaging Machine", "PACK"), PackagingMachine, 100);
            // The structural catch-all (catalog Part D "Not printed"): every category at LOW, so
            // any printer profile's Item rule (+20000) always wins the tie for something it prints.
            Cats(Bag(d, "Not Printed", "RAW"), 10,
                "Ores", "Ices", "Default", "Resources", "Tools", "Food", "Clothing",
                "Kits", "Storage", "Appliances", "Atmospherics");
            return d;
        }

        // ================= 2. BY CATEGORY (catalog Part B) =================

        /// <summary>One Bag Profile per game <c>SortingClass</c> - the honest 11 - plus the two
        /// places the catalog says that taxonomy simply lies:
        /// <list type="bullet">
        /// <item>an <b>Electronics</b> profile built from Slot.Class rules (catalog C5's own rule
        /// list), because the game has no electronics category at all and every board, chip,
        /// cartridge and battery otherwise lands in the ~210-item <c>Default</c> junk drawer;</item>
        /// <item>a <c>UIAClass</c> catch-all on <b>Tools</b> and <b>Kits</b> (plan SS3.2, FlorpyDorp
        /// Q1) so a new or modded tool/kit whose SortingClass is unset still lands somewhere sane.
        ///
        /// <para>READ THE PRIORITY CORRECTLY. The literal <c>10</c> on those two rules is NOT a
        /// low-priority backstop, whatever it looks like next to the <c>50</c>s around it: rule KINDS
        /// are ranked by a fixed offset in <see cref="BagProfile.Match"/> (Item +20000, UIAClass
        /// +15000, Slot.Class +10000, Category +0), so priority-10 UIAClass scores 15010 and OUTRANKS
        /// every Category rule in this set — and in every other set the player has, since matching
        /// runs across all profiles. These two rules WIN their ties; they do not lose them. No live
        /// misroute exists today only because <c>UIASort.Classify</c> derives Tool/Kit from the same
        /// SortingClass, so the two never disagree on vanilla content. A MODDED item classified
        /// <c>UIAClass.Kit</c> while carrying <c>SortingClass=Atmospherics</c> WOULD be poached out of
        /// the Atmospherics bag by the Kits one. Adding a third such rule needs that checked, not
        /// assumed — and if a genuine tie-breaker-only rule is ever wanted, the offsets, not the
        /// number, are what would have to change.</para>
        ///
        /// <para>Only these two for exactly that reason: every other UIA class overlaps a second
        /// bucket here (UIAClass.Ore covers Ices, UIAClass.Material covers Resources AND stackable
        /// frames, UIAClass.Storage covers backpacks that are SortingClass=Clothing), and a rule that
        /// poaches another bag's items is worse than one that catches nothing.</para></item>
        /// </list></summary>
        private static StowProfileDoc BuildByCategory()
        {
            var d = Doc(ByCategory, "One bag per game category, the way Stationeers itself sorts items - plus an Electronics bag, because the game has no category for circuit boards, chips and batteries.");
            Classes(Cats(Bag(d, "Tools", "TOOL"), 50, "Tools"), 10, "Tool");
            Cats(Bag(d, "Resources", "RES"), 50, "Resources");
            Classes(Cats(Bag(d, "Kits", "KIT"), 50, "Kits"), 10, "Kit");
            Cats(Bag(d, "Food", "FOOD"), 50, "Food");
            Cats(Bag(d, "Clothing", "CLTH"), 50, "Clothing");
            Cats(Bag(d, "Appliances", "APPL"), 50, "Appliances");
            Cats(Bag(d, "Atmospherics", "ATMO"), 50, "Atmospherics");
            Cats(Bag(d, "Storage", "STOR"), 50, "Storage");
            Cats(Bag(d, "Ores", "ORE"), 50, "Ores");
            Cats(Bag(d, "Ices", "ICE"), 50, "Ices");
            // Catalog C5's rule list verbatim. Slot.Class rules carry +10000, so these always beat
            // the Category=Default rule on "Other" below without needing a priority fight.
            Slots(Bag(d, "Electronics", "ELEC"), 60,
                "Circuitboard", "Motherboard", "Cartridge", "ProgrammableChip",
                "DataDisk", "SoundCartridge", "SensorProcessingUnit", "Battery");
            Cats(Bag(d, "Other", "MISC"), 10, "Default");
            return d;
        }

        // ================= 3. ASCENDED (catalog Part C; formerly "Stationpedia Ascended") =================

        /// <summary>FlorpyDorp's own 9-bag layout, transcribed rule for rule from catalog C1-C9.
        /// Deliberately NO <c>UIAClass</c> rules: Part C was reviewed and approved as written, and
        /// every UIA class that looks like a fit here also poaches a sibling bag (UIAClass.Material
        /// would pull Milk and Sugar into "Materials"; UIAClass.Tank would pull the portable
        /// AC/scrubber/generator into "Canisters", which catalog judgment call 7 explicitly leaves
        /// in Misc). The catalog's flagged consequences are inherited as-is: Dirt Canister reports
        /// Slot.Class=Ore so it lands in Ingots and Ores, Ices are grouped with mined material
        /// rather than with gases, and Misc is large by construction (~250-300 items).</summary>
        private static StowProfileDoc BuildAscended()
        {
            var d = Doc(Ascended, "FlorpyDorp's own nine-bag layout: paints, sheet materials, frames and walls, ingots and ores, electronics, liquids and gases, cables and pipes, canisters, and one Misc for the rest.");
            Items(Bag(d, "Paints", "PNT"), Paints, 100);
            Items(Bag(d, "Materials", "MAT"), Materials, 100);
            Items(Bag(d, "Frames and Walls", "WALL"), FramesAndWalls, 100);
            Cats(Slots(Bag(d, "Ingots and Ores", "ORE"), 60, "Ingot", "Ore"), 50, "Ores", "Ices");
            Slots(Bag(d, "Electronics", "ELEC"), 60,
                "Circuitboard", "Motherboard", "Cartridge", "ProgrammableChip",
                "DataDisk", "SoundCartridge", "SensorProcessingUnit", "Battery");
            Slots(Bag(d, "Liquids and Gases", "GAS"), 60, "GasFilter", "LiquidBottle");
            Items(Bag(d, "Cables and Pipes", "PIPE"), CablesAndPipes, 100);
            Items(Slots(Bag(d, "Canisters", "CAN"), 60, "GasCanister", "LiquidCanister", "Portables"), CanisterKits, 100);
            Cats(Bag(d, "Misc", "MISC"), 10,
                "Default", "Tools", "Food", "Clothing", "Appliances", "Storage", "Resources", "Kits");
            return d;
        }

        // ================= 4. STARTER (catalog Part E) =================

        /// <summary>One bag, four category rules. Deliberately NO Kits/Default/Resources - those
        /// would swallow every wall kit, battery and access card the moment you picked one up,
        /// which defeats the point of a starter bag (get the ore/ice/tool/food haul under control
        /// first).</summary>
        private static StowProfileDoc BuildStarter()
        {
            var d = Doc(Starter, "One bag for the early game: the ore, ice, tool and food haul. Nothing else is claimed, so a second bag can be added later without a fight.");
            Cats(Bag(d, "Starter Haul", "HAUL"), 50, "Ores", "Ices", "Tools", "Food");
            return d;
        }

        // ================= data =================

        // ---- catalog Part D: one array per fabricator, its own recipe roster ----

        // Autolathe - 64 item(s)
        private static readonly string[] Autolathe =
        {
            "ItemIronFrames", "ItemIronSheets", "ItemPlasticSheets", "ItemGlassSheets",
            "ItemStelliteGlassSheets", "ItemSteelSheets", "ItemAstroloySheets", "ItemSteelFrames",
            "ItemKitWallIron", "ItemKitRailing", "ItemKitCompositeCladding", "ItemKitWall",
            "ItemKitReinforcedWindows", "ItemKitWindowShutter", "ItemKitLadder", "ItemCableCoil",
            "ItemKitFurnace", "ItemKitArcFurnace", "ItemKitElectronicsPrinter", "ItemKitRocketManufactory",
            "ItemKitSecurityPrinter", "ItemKitBlastDoor", "ItemKitRobotArmDoor", "ItemKitFurniture",
            "ItemKitTables", "ItemKitChairs", "ItemKitBeds", "ItemKitSorter", "ItemKitHydraulicPipeBender",
            "ItemKitAutolathe", "ItemKitDoor", "ItemKitInteriorDoors", "ItemKitWallArch", "ItemKitWallFlat",
            "ItemKitWallGeometry", "ItemKitWallPadded", "ItemKitLocker", "ItemKitSign", "ItemKitStairs",
            "ItemKitStairwell", "ItemKitStacker", "ItemEmptyCan", "CardboardBox", "CardboardBoxLarge",
            "ItemKitSDBHopper", "KitSDBSilo", "ItemKitCompositeFloorGrating", "ItemKitToolManufactory",
            "ItemKitRecycler", "ItemKitCentrifuge", "KitStructureCombustionCentrifuge", "ItemKitDeepMiner",
            "ItemKitCombustionDeepMiner", "ItemKitCrateMount", "ItemKitCrate", "ItemKitCrateMkII",
            "ItemBurgerBox", "ItemEggCarton", "ItemCoffeeMug", "ItemKitFlagODA", "ItemKitAccessBridge",
            "ApplianceBobbleHeadBasicSuit", "ApplianceBobbleHeadHardSuit", "ApplianceBobbleHeadMarine",
        };

        // Tool Manufactory - 117 item(s)
        private static readonly string[] ToolManufactory =
        {
            "ItemMKIICrowbar", "ItemMKIIWrench", "ItemMKIIDuctTape", "ItemMKIIDrill", "ItemWasteBagEmpty",
            "ItemMKIIScrewdriver", "ItemMKIIArcWelder", "ItemMKIIAngleGrinder", "ItemMKIIWireCutters",
            "ItemMKIIMiningDrill", "ItemSprayGun", "ItemCrowbar", "ItemWearLamp", "ItemFlashlight",
            "ItemDisposableBatteryCharger", "ItemBeacon", "ItemWrench", "ItemSurvivalBelt", "ItemDuctTape",
            "ItemDrill", "ToyLuna", "ItemScrewdriver", "ItemArcWelder", "ItemWeldingTorch",
            "ItemAngleGrinder", "ItemWireCutters", "ItemLabeller", "ItemOreDetector", "ItemRemoteDetonator",
            "ItemMiningDrill", "ItemMiningDrillPneumatic", "ItemLiquidVacuum", "ItemMiningDrillHeavy",
            "ItemPickaxe", "ItemMiningBelt", "ItemMiningBeltMKII", "ItemMiningBackPack",
            "ItemHardMiningBackPack", "ItemTerrainManipulator", "ItemDirtCanister", "ItemGasMask",
            "ItemHardHat", "ItemSpaceHelmet", "ItemIcarusHelmet", "ItemSpacepack", "ItemJetpackBasic",
            "ItemEvaSuit", "ItemIcarusSuit", "ItemToolBelt", "ItemMkIIToolbelt", "UniformCommander",
            "UniformOrangeJumpSuit", "UniformMarine", "ItemClothingBagOveralls_Aus",
            "ItemClothingBagOveralls_Brazil", "ItemClothingBagOveralls_Paintable",
            "ItemClothingBagOveralls_Canada", "ItemClothingBagOveralls_China", "ItemClothingBagOveralls_EU",
            "ItemClothingBagOveralls_France", "ItemClothingBagOveralls_Germany",
            "ItemClothingBagOveralls_Japan", "ItemClothingBagOveralls_Korea", "ItemClothingBagOveralls_NZ",
            "ItemClothingBagOveralls_Russia", "ItemClothingBagOveralls_SouthAfrica",
            "ItemClothingBagOveralls_UK", "ItemClothingBagOveralls_Ukraine", "ItemClothingBagOveralls_US",
            "ItemRoadFlare", "FlareGun", "ItemChemLightBlue", "ItemChemLightGreen", "ItemChemLightRed",
            "ItemChemLightWhite", "ItemChemLightYellow", "ItemIgniter", "ItemHardSuit", "ItemSuitHARM",
            "ItemSuitHelmetHARM", "ItemReusableFireExtinguisher", "ItemHardsuitHelmet",
            "ItemMarineBodyArmor", "ItemMarineHelmet", "ItemNVG", "ItemSensorLenses",
            "ItemSensorProcessingUnitOreScanner", "ItemSensorProcessingUnitMesonScanner",
            "ItemSensorProcessingUnitCelestialScanner", "ItemGlasses", "ItemHardBackpack",
            "ItemHardJetpack", "ItemFlagSmall", "ItemKitDynamicAFrameStripes", "ItemKitDynamicAFrameWIP1",
            "ItemKitDynamicBarrier", "ItemKitDynamicChannelizer", "ItemKitDynamicWorkCone",
            "ItemBasketBall", "ItemKitBasket", "ItemPlantSampler", "ItemSprayCanBlack", "ItemSprayCanBlue",
            "ItemSprayCanBrown", "ItemSprayCanGreen", "ItemSprayCanGrey", "ItemSprayCanKhaki",
            "ItemSprayCanOrange", "ItemSprayCanPink", "ItemSprayCanPurple", "ItemSprayCanRed",
            "ItemSprayCanWhite", "ItemSprayCanYellow", "ItemSprayCanMetallicBronze",
            "ItemSprayCanMetallicGold", "ItemSprayCanMetallicObsidian", "ItemSprayCanMetallicSilver",
        };

        // Security Printer - 15 item(s)
        private static readonly string[] SecurityPrinter =
        {
            "CartridgeAccessController", "AccessCardBlack", "AccessCardBlue", "AccessCardBrown",
            "AccessCardGray", "AccessCardGreen", "AccessCardKhaki", "AccessCardOrange", "AccessCardPink",
            "AccessCardPurple", "AccessCardRed", "AccessCardWhite", "AccessCardYellow", "ItemExplosive",
            "ItemMiningCharge",
        };

        // Electronics Printer - 127 item(s)
        private static readonly string[] ElectronicsPrinter =
        {
            "ItemKitGrowLight", "ItemBatteryCell", "ItemBatteryCellLarge", "Battery_Wireless_cell",
            "Battery_Wireless_cell_Big", "ItemKitPowerTransmitter", "ItemKitPowerTransmitterOmni",
            "ItemBatteryCellNuclear", "ItemHEMDroidRepairKit", "ItemBatteryCharger",
            "ItemBatteryChargerSmall", "CartridgeAtmosAnalyser", "CartridgePlantAnalyser",
            "CartridgeNetworkAnalyser", "ItemSoundCartridgeBass", "ItemSoundCartridgeDrums",
            "ItemSoundCartridgeLeads", "ItemSoundCartridgeSynth", "CartridgeOreScannerColor",
            "ItemKitAIMeE", "ItemKitFridgeSmall", "ItemKitFridgeBig", "CartridgeConfiguration",
            "CartridgeTracker", "CartridgeDeepMiner", "CircuitboardAirControl",
            "CircuitboardAdvAirlockControl", "CircuitboardAirlockControl", "CircuitboardDoorControl",
            "CircuitboardGasDisplay", "CircuitboardModeControl", "CircuitboardPowerControl",
            "CircuitboardSolarControl", "CircuitboardGraphDisplay", "CircuitboardHashDisplay",
            "ItemAreaPowerControl", "ItemCableAnalyser", "ItemCableCoilHeavy", "ItemCableCoilSuperHeavy",
            "ItemCableFuse", "ItemDataDisk", "ItemFlashingLight", "ItemKitBattery", "ItemKitBatteryLarge",
            "ItemKitComputer", "ItemKitConsole", "ItemKitLogicInputOutput", "ItemKitLogicMemory",
            "ItemKitSpeaker", "ItemKitLogicProcessor", "ItemKitMusicMachines", "ItemKitLogicTransmitter",
            "ItemKitLogicSwitch", "ItemIntegratedCircuit10", "ItemKitLogicCircuit", "ItemPowerConnector",
            "ItemKitPressurePlate", "ItemKitSolidGenerator", "ItemKitGasGenerator", "ItemKitSensor",
            "ItemElectronicParts", "ItemKitWeatherStation", "ItemKitSolarPanelBasic", "ItemKitSolarPanel",
            "ItemKitStirlingEngine", "ItemKitSolarPanelBasicReinforced", "ItemKitSolarPanelReinforced",
            "PortableSolarPanel", "ItemKitTransformer", "ItemKitTransformerSmall", "ItemTablet",
            "ItemAdvancedTablet", "ItemLaptop", "ItemWallLight", "MotherboardLogic", "MotherboardRockets",
            "MotherboardMap", "MotherboardProgrammableChip", "MotherboardSorter", "MotherboardComms",
            "ItemKitBeacon", "ItemKitElevator", "ItemKitHydroponicStation", "ItemKitSmallSatelliteDish",
            "ItemKitSatelliteDish", "ItemKitLargeSatelliteDish", "ItemKitLandingPadBasic",
            "ItemKitLandingPadAtmos", "ItemKitLandingPadWaypoint", "ItemKitHarvie",
            "ItemKitDynamicGenerator", "ItemKitVendingMachine", "ItemKitVendingMachineRefrigerated",
            "ItemKitAutomatedOven", "ItemKitAdvancedPackagingMachine", "ItemKitAdvancedComposter",
            "PortableComposter", "ItemKitUprightWindTurbine", "ItemKitWindTurbine", "ElectronicPrinterMod",
            "AutolathePrinterMod", "ToolPrinterMod", "PipeBenderMod", "ItemKitAdvancedFurnace",
            "ApplianceMicrowave", "ApplianceTabletDock", "AppliancePackagingMachine",
            "ApplianceDeskLampRight", "ApplianceDeskLampLeft", "ApplianceReagentProcessor",
            "ApplianceChemistryStation", "ItemKitAutoMinerSmall", "ItemKitHorizontalAutoMiner",
            "ItemCreditCard", "AppliancePlantGeneticAnalyzer", "AppliancePlantGeneticSplicer",
            "AppliancePlantGeneticStabilizer", "ItemKitGroundTelescope", "ItemKitLinearRail",
            "ItemKitRoboticArm", "ItemKitLarreDockAtmos", "ItemKitLarreDockBypass", "ItemKitLarreDockCargo",
            "ItemKitLarreDockCollector", "ItemKitLarreDockHydroponics", "ItemKitRoverMKI", "DynamicLight",
        };

        // Hydraulic Pipe Bender - 130 item(s)
        private static readonly string[] HydraulicPipeBender =
        {
            "ItemActiveVent", "ItemGasCanisterEmpty", "ItemKitWaterBottleFiller", "ItemKitDrinkingFountain",
            "ItemWaterBottle", "ItemGasCanisterSmart", "ItemLiquidCanisterSmart", "ItemLiquidCanisterEmpty",
            "ItemKitSuitStorage", "ItemKitToilet", "ItemGasFilterCarbonDioxide", "ItemGasFilterAlcohol",
            "ItemGasFilterHCl", "ItemGasFilterHelium", "ItemGasFilterHydrazine", "ItemGasFilterHydrogen",
            "ItemGasFilterOzone", "ItemGasFilterPollutedWater", "ItemGasFilterSalt", "ItemGasFilterSilanol",
            "ItemGasFilterPollutants", "ItemGasFilterNitrogen", "ItemGasFilterOxygen",
            "ItemGasFilterVolatiles", "ItemGasFilterNitrousOxide", "ItemGasFilterWater",
            "ItemGasFilterCarbonDioxideM", "ItemGasFilterAlcoholM", "ItemGasFilterHClM",
            "ItemGasFilterHeliumM", "ItemGasFilterHydrazineM", "ItemGasFilterHydrogenM",
            "ItemGasFilterOzoneM", "ItemGasFilterPollutedWaterM", "ItemGasFilterSaltM",
            "ItemGasFilterSilanolM", "ItemGasFilterPollutantsM", "ItemGasFilterNitrogenM",
            "ItemGasFilterOxygenM", "ItemGasFilterVolatilesM", "ItemGasFilterNitrousOxideM",
            "ItemGasFilterWaterM", "ItemGasFilterCarbonDioxideL", "ItemGasFilterAlcoholL",
            "ItemGasFilterHClL", "ItemGasFilterHeliumL", "ItemGasFilterHydrazineL",
            "ItemGasFilterHydrogenL", "ItemGasFilterOzoneL", "ItemGasFilterPollutedWaterL",
            "ItemGasFilterSaltL", "ItemGasFilterSilanolL", "ItemGasFilterPollutantsL",
            "ItemGasFilterNitrogenL", "ItemGasFilterOxygenL", "ItemGasFilterVolatilesL",
            "ItemGasFilterNitrousOxideL", "ItemGasFilterWaterL", "ItemKitPipeUtility",
            "ItemKitPipeUtilityLiquid", "ItemAdhesiveInsulation", "ItemKitInsulatedPipeUtility",
            "ItemKitInsulatedPipeUtilityLiquid", "ItemHydroponicTray", "ItemKitPlanter", "ItemKitAirlock",
            "ItemKitAirlockGate", "ItemKitAtmospherics", "ItemKitLiquidFiltration", "ItemKitWaterPurifier",
            "ItemKitChute", "ItemKitStandardChute", "ItemKitPipe", "ItemKitInsulatedPipe",
            "ItemKitInsulatedLiquidPipe", "ItemKitPipeLiquid", "ItemKitRegulator", "ItemKitLiquidRegulator",
            "ItemKitTank", "ItemKitLiquidTank", "ItemKitTankInsulated", "ItemKitLiquidTankInsulated",
            "ItemPassiveVent", "ItemPassiveVentInsulated", "ItemPipeCowl", "ItemPipeAnalyizer",
            "ItemPipeIgniter", "ItemLiquidPipeAnalyzer", "ItemPipeDigitalValve",
            "ItemWaterPipeDigitalValve", "ItemPipeGasMixer", "ItemPipeLabel", "ItemPipeMeter",
            "ItemWaterPipeMeter", "ItemLiquidDrain", "ItemKitPipeRadiator",
            "ItemKitLargeExtendableRadiator", "ItemKitPassiveLargeRadiatorLiquid",
            "ItemKitPassiveLargeRadiatorGas", "ItemKitPoweredVent", "ItemKitLargeDirectHeatExchanger",
            "ItemKitPassthroughHeatExchanger", "ItemKitSmallDirectHeatExchanger",
            "ItemKitEvaporationChamber", "ItemKitPipeRadiatorLiquid", "ItemPipeValve",
            "ItemLiquidPipeValve", "ItemPipeVolumePump", "ItemKitTurboVolumePump",
            "ItemKitLiquidTurboVolumePump", "ItemLiquidPipeVolumePump", "ItemLiquidPipeHeater",
            "ItemPipeHeater", "ItemKitPortablesConnector", "ItemWallCooler", "ItemWaterWallCooler",
            "ItemWallHeater", "ItemKitSleeper", "ItemKitCryoTube", "ItemDynamicAirCon",
            "ItemDynamicScrubber", "ItemKitDynamicHydroponics", "ItemKitPipeOrgan", "ItemKitIceCrusher",
            "ItemKitShower", "ApplianceSeedTray", "ItemKitDynamicCanister", "ItemKitDynamicGasTankAdvanced",
            "ItemKitDynamicLiquidCanister", "ItemKitDynamicMKIILiquidCanister",
        };

        // Rocket Manufactory - 41 item(s)
        private static readonly string[] RocketManufactory =
        {
            "ItemKitFuselage", "ItemKitLaunchTower", "ItemKitLaunchMount", "ItemKitLaunchMountOrbital",
            "ItemKitChuteUmbilical", "ItemKitElectricUmbilical", "ItemKitLiquidUmbilical",
            "ItemKitGasUmbilical", "ItemKitRocketBattery", "ItemKitRocketGasFuelTank",
            "ItemKitRocketLiquidFuelTank", "ItemKitRocketAvionics", "ItemKitRocketCelestialTracker",
            "ItemKitRocketDatalink", "ItemKitRocketCircuitHousing", "ItemKitRocketCargoStorage",
            "ItemKitRocketMiner", "ItemKitRocketScanner", "ItemRocketScanningHead",
            "ItemRocketDeepScanningHead", "ItemRocketMiningDrillHead", "ItemRocketMiningDrillHeadMineral",
            "ItemRocketMiningDrillHeadIce", "ItemRocketMiningDrillHeadDurable",
            "ItemRocketMiningDrillHeadLongTerm", "ItemRocketMiningDrillHeadHighSpeedIce",
            "ItemRocketMiningDrillHeadHighSpeedMineral", "ItemKitGovernedGasRocketEngine",
            "ItemKitPressureFedGasEngine", "ItemKitPressureFedLiquidEngine", "ItemKitPumpedLiquidEngine",
            "ItemKitRocketTransformerSmall", "ItemKitRocketAtmospherics", "ItemKitPayloadDeliveryContainer",
            "ItemKitOrbitalLaunchMountPayload", "ItemKitRocketLargePayloadBay", "ItemKitCrewParts",
            "ItemKitCrewModuleElectronics", "ItemKitCrewModuleCableConnector", "ItemKitCrewModuleChair",
            "ItemKitCrewModuleScreen",
        };

        // Furnace - 14 item(s)
        private static readonly string[] Furnace =
        {
            "ItemCharcoal", "ItemSolidFuel", "ItemSiliconIngot", "ItemIronIngot", "ItemGoldIngot",
            "ItemCopperIngot", "ItemSilverIngot", "ItemLeadIngot", "ItemNickelIngot", "ItemSteelIngot",
            "ItemElectrumIngot", "ItemInvarIngot", "ItemConstantanIngot", "ItemSolderIngot",
        };

        // Advanced Furnace - 5 item(s)
        private static readonly string[] AdvancedFurnace =
        {
            "ItemAstroloyIngot", "ItemHastelloyIngot", "ItemInconelIngot", "ItemWaspaloyIngot",
            "ItemStelliteIngot",
        };

        // Centrifuge - 11 item(s)
        private static readonly string[] Centrifuge =
        {
            "ItemBiomass", "ItemIronOre", "ItemGoldOre", "ItemCopperOre", "ItemCoalOre", "ItemUraniumOre",
            "ItemSilverOre", "ItemLeadOre", "ItemNickelOre", "ItemSiliconOre", "ItemCobaltOre",
        };

        // Chemistry Set - 3 item(s)
        private static readonly string[] ChemistrySet =
        {
            "ItemPillHeal", "ItemPillStun", "ItemMilk",
        };

        // Reagent Grinder - 4 item(s)
        private static readonly string[] ReagentGrinder =
        {
            "ItemFlour", "ItemSugar", "ItemCocoaPowder", "ItemSoyOil",
        };

        // Microwave - 19 item(s)
        private static readonly string[] Microwave =
        {
            "ItemMuffin", "ItemCerealBar", "ItemChocolateCerealBar", "ItemPotatoBaked", "ItemBurger",
            "ItemBreadLoaf", "ItemFries", "ItemPumpkinPie", "ItemCookedTomato", "ItemCookedMushroom",
            "ItemCookedCorn", "ItemCookedRice", "ItemCookedPumpkin", "ItemCookedPowderedEggs",
            "ItemCookedCondensedMilk", "ItemCookedSoybean", "ItemChocolateBar", "ItemPlainCake",
            "ItemChocolateCake",
        };

        // Packaging Machine - 9 item(s)
        private static readonly string[] PackagingMachine =
        {
            "ItemTomatoSoup", "ItemPumpkinSoup", "ItemCornSoup", "ItemCannedMushroom",
            "ItemCannedPowderedEggs", "ItemFrenchFries", "ItemCannedRicePudding", "ItemCannedCondensedMilk",
            "ItemCannedEdamame",
        };

        // ---- catalog Part C: FlorpyDorp's item-listed bags ----

        // C1 Paints - all 16 spray cans. Item rules, not Slot.Class=Bottle, which would also
        // catch Hand Sanitizer.
        private static readonly string[] Paints =
        {
            "ItemSprayCanBlack", "ItemSprayCanBlue", "ItemSprayCanMetallicBronze", "ItemSprayCanBrown",
            "ItemSprayCanMetallicGold", "ItemSprayCanGreen", "ItemSprayCanGrey", "ItemSprayCanKhaki",
            "ItemSprayCanMetallicObsidian", "ItemSprayCanOrange", "ItemSprayCanPink", "ItemSprayCanPurple",
            "ItemSprayCanRed", "ItemSprayCanMetallicSilver", "ItemSprayCanWhite", "ItemSprayCanYellow",
        };

        // C2 Materials - every sheet the Autolathe prints.
        private static readonly string[] Materials =
        {
            "ItemIronSheets", "ItemSteelSheets", "ItemPlasticSheets", "ItemGlassSheets",
            "ItemStelliteGlassSheets", "ItemAstroloySheets",
        };

        // C3 Frames and Walls - all SortingClass=Kits + Slot.Class=None, i.e. indistinguishable
        // from a rocket-engine kit by any rule other than naming each one.
        private static readonly string[] FramesAndWalls =
        {
            "ItemIronFrames", "ItemSteelFrames", "ItemKitWallFlat", "ItemKitWallArch",
            "ItemKitWallGeometry", "ItemKitWallIron", "ItemKitWallPadded", "ItemKitWall",
            "ItemKitCompositeCladding", "ItemKitReinforcedWindows", "ItemKitWindowShutter",
            "ItemKitCompositeFloorGrating", "ItemKitDoor", "ItemKitInteriorDoors", "ItemKitBlastDoor",
            "ItemKitAirlock", "ItemKitAirlockGate", "ItemKitRailing", "ItemKitLadder", "ItemKitStairs",
            "ItemKitStairwell",
        };

        // C7 Cables and Pipes - the 3 coils (Slot.Class=Tool, so they need the explicit
        // exception the shipped "Electrical" starter always needed) + the whole pipe family.
        private static readonly string[] CablesAndPipes =
        {
            "ItemCableCoil", "ItemCableCoilHeavy", "ItemCableCoilSuperHeavy", "ItemKitPipe",
            "ItemKitPipeLiquid", "ItemKitInsulatedPipe", "ItemKitInsulatedLiquidPipe",
            "ItemKitInsulatedPipeUtility", "ItemKitInsulatedPipeUtilityLiquid", "ItemKitPipeUtility",
            "ItemKitPipeUtilityLiquid", "ItemKitPipeOrgan", "ItemKitPipeRadiator",
            "ItemKitPipeRadiatorLiquid", "ItemPipeDigitalValve", "ItemWaterPipeDigitalValve",
            "ItemPipeGasMixer", "ItemPipeValve", "ItemLiquidPipeValve", "ItemPipeMeter",
            "ItemWaterPipeMeter", "ItemPipeAnalyizer", "ItemLiquidPipeAnalyzer", "ItemPipeIgniter",
            "ItemPipeLabel", "ItemPipeCowl", "ItemPipeHeater", "ItemLiquidPipeHeater", "ItemPipeVolumePump",
            "ItemLiquidPipeVolumePump", "ItemKitTurboVolumePump", "ItemKitLiquidTurboVolumePump",
        };

        // C8 Canisters - the tank/canister KIT exceptions; the vessels themselves come in via
        // the three Slot.Class rules.
        private static readonly string[] CanisterKits =
        {
            "ItemKitTank", "ItemKitLiquidTank", "ItemKitTankInsulated", "ItemKitLiquidTankInsulated",
            "ItemKitDynamicCanister", "ItemKitDynamicGasTankAdvanced", "ItemKitDynamicLiquidCanister",
            "ItemKitDynamicMKIILiquidCanister",
        };
    }
}
